### ISSUE TITLE
Block protector and inventory items

### ISSUE THREAD

**Issue by Flexo013** [McJtyMods/RFTools#1113]
This is a reopening of the issue described in #649, since it is still present.

I'm playing FTB presents Skyfactory 3 version 3.0.8 at the moment and it does not allow you to protect any block that has a GUI.
MC Version: 1.10.2
RFTools Version: 1.1x-5.87
RFTools Control Version: 1.1x-1.6.6
RFTools Dimensions Version: 1.1x-4.54

To reproduce this do the following:
Have a Block Protector with a vanilla chest on one side and a Vacuum Chest form Ender IO on the other side.
Right-click the Block Protector with a Smart Wrench in Focus mode (orange) to select it. Now you see the protected blocks.
Right-clicking either chest while holding the orange smart wrench just opens the chest's GUI.
Sneak + right-clicking either chest while holding the orange smart wrench just clears the Block Protector we selected earlier.
(Any combination of hotkey and mouse button does not protect the chest the you are clicking on.)

I even tested if I could protect a chest if I prevented the GUI from opening by placing a block above the vanilla chest. Even in this case nothing happens. The chest does not get protected and the chest is not opened.

**Comment by McJty** [comment]
Fixed next release (using sneak wrench on the chest will work again)

**Comment by Flexo013** [comment]
Awesome! Thanks for the quick fix!

**Comment by PongoSapiens** [comment]
This issue appears to have returned in 1.12.2 RFTools version 7.13

**Comment by uehlbran** [comment]
This issue is still present and hasn't been fixed.

Version: 1.12.2-7.14

**Comment by josephcsible** [comment]
Version 7.22 is out now. Can you retest on it?

**Comment by uehlbran** [comment]
Yes. One sec please.

**Comment by uehlbran** [comment]
Edit: Looking like I'm having issues with Direwolf20 1.12.2 and mcjtylib 1.60, xnet 1.60 rftools 7.22 or deep resonance. After installing these my game just crashes instantly.

Crash log:https://pastebin.com/2mtRbGTK

Will try to update deep resonance to 1.60 and the latest version of elecCore.

Game still crashes after updating eleCCore to 1.12.2-1.8.434 and DeepResonance 1.60.

Crash Log: https://pastebin.com/gJ05msAz

Not sure what to do?

**Comment by josephcsible** [comment]
Update RFTools Dimensions too.

**Comment by uehlbran** [comment]
Ok. Updated. The issue still persists. I have the wrench in focus mode and have tried to sneak + right-click, right-click, and also tried left click variants of those and it still will not block protect.

**Comment by josephcsible** [comment]
> mcjtylib 1.60

I assume you meant McJtyLib 2.6.1 here.

Anyway, when I try to reproduce the problem in a world with just MC 1.12.2, Forge 2555, McJtyLib 2.6.1, and RFTools 7.22, I can protect chests fine by sneak-right-clicking. It might be a conflict with one of your other mods that's making it not work for you. Can you see if that's the case, and if so, try to figure out which mod it is?

**Comment by uehlbran** [comment]
Yes, McJtyLib version 2.6.1 is what I meant. I'm also using the same version of forge. I can try to see if it's another mod. I'll also try in a new world to see if anything is different in that.

**Comment by josephcsible** [comment]
Please open a new issue for the spawner.

**Comment by uehlbran** [comment]
I disabled any mods that should have to do with muse clicks (inventory sorter, mousetweaks), but the issue still happens. I'm not sure whats causing it. It applies to any block with an inventory or gui though. Any mods that come to mind that I should try to disable?

**Comment by josephcsible** [comment]
Coremods are always a good place to start:
```
  FMLPlugin (elulib-0.1.10.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.5.7.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  AstralCore (astralsorcery-1.12.2-1.8.2.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b129.jar)
  SFRCore (SolarFluxReborn_1.12.2-3.42r.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.9.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.3.0.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
```
You're probably going to have to do a [binary search](https://en.wikipedia.org/wiki/Binary_search_algorithm) (i.e., disable half of your mods at a time to figure out which half the problem is in, and repeat until you get it down to 1) to find it.

**Comment by spitefulcoder** [comment]
I don't work for ftb infinity evolved either

**Comment by MichaelHillcox** [comment]
Thank you for taking the time to create this issue, as we're no longer supporting versions below `1.12`, I'm going to go ahead and close it but if this bug seems to continue over to newer versions, please do report it again so we can investigate the issue further.
