### ISSUE TITLE
Major lag caused by Tier 3 crafters

### ISSUE THREAD

**Issue by SubtypeZero** [McJtyMods/RFTools#1444]
One of the players on my server placed down about 20 of the T3 crafters and they seem to be taking roughly 10% of the server tick when most of them are not even running. Since the crafters seem to mostly run on the shared code that handles all of the actual crafting and updating, this is possibly an issue with all crafters (regardless of tier).

**Comment by McJty** [comment]
Not sure much can be done about this. The crafters simply are a pretty expensive block and you shouldn't overdo them. It is the same with spamming any other block that has to do a lot of calculations

**Comment by SubtypeZero** [comment]
I haven't looked into it too much, but if it can't be optimized in it's current form, then wouldn't it at least be possible to do some of the calculations in another thread and try to avoid doing everything on the main server thread? Once again, I haven't looked too far into this particular issue, so correct me if I'm wrong. I just don't see how automatic crafting should be taking that many server resources. I'm sure it's complicated but I'd like to see if there's any way it can be improved upon with the goal of optimizing for performance.

**Comment by SubtypeZero** [comment]
I had that particular player reduce it down to four T3 crafters and 3/4 of them still show up on my list of top 5 single entities causing lag. The total percent of the tick for those three `CrafterBlockTileEntity3'`s were taking about 9.5% of the server tick (according to the [TickProfiler](https://github.com/MinimallyCorrect/TickProfiler)).

**Comment by McJty** [comment]
Is he enabling 'fast speed' for them? Disabling that might improve matters.

Doing calculations in a thread is not really possible since Minecraft is not multithreaded and the crafter has to access a lot of data. I will however try to profile the crafters to see if there is anything I can do.

**Comment by SubtypeZero** [comment]
Yes, he did have them on 'fast' but I've seen quite a bit of lag from these even with them on 'slow'. I'll certainly change that and see if helps. I appreciate the effort, I'd like to see these working faster since they're pretty much the only decent option for players who are looking to automate crafting.

**Comment by Fatmice** [comment]
Are the T3 crafters doing recursive recipes?  If so I suggest using the compactor mod.  If you're simply making cobblestone, the mod has a creative block that generates lag-free tons of cobblestone.  I suggest using that instead of generating your own cobblestone with things like extra utilities transfer nodes.

Too bad steve's factory manager or hilburn's advance crafting manager doesn't work with 1.12.x =(  Those are much more tps friendly.

**Comment by McJty** [comment]
I did a profile on a series of T3 crafters at full speed and couldn't find any bottleneck. I think this is just to be expected when you have a lot of something doing something

**Comment by SubtypeZero** [comment]
I definitely see a big difference between leaving them on "fast" vs. leaving them on "slow", but I still don't feel that they should be taking up much of the server resources.

**Comment by Mohron** [comment]
I've seen this issue as well. Even if no crafting is being done with the crafters on slow, they still show as one of the most significant single source of tick time. Here's a screen shot of them using lag googles:

![](https://cdn.discordapp.com/attachments/412013549041352705/418221187123118090/2018-02-27_20.41.20.png)

**Comment by McJty** [comment]
To @Mohron , what version?

**Comment by Mohron** [comment]
From Forever Stranded Lost Souls:
RFTools 1.12-7.29
McJtyLib 1.12-2.6.4

I've been experiencing issues with the crafters using a large portion of the tick time with multiple  1.12.2 versions though.

**Comment by josephcsible** [comment]
Can you reproduce this in single player, or only on servers?

**Comment by kerzenhans** [comment]
Since this week our ATM3 (v5.8) server had LagGoggles added and everybody has been streamlining their bases. As everbody (10-20) was using 2-3 T3 ones to process their Mystical Agriculture, guess the result.
Hands down, I really like the crafter and as has been said, it has to access a lot of data.

Inventory handling;
Lets look at the mystical usecase. Typically it sits there, waiting for the ingredients, scanning its inventory, which is scanning every single slot. ( I think minecolonies hit that wall with their warehouse, scanning 20+ chests. They wrote their own inventory handler afterwards.).
But writing  an inventory overly to efficiently handle ingredient requests is outside of quick.
A quick option would be to have the possibility to instead of ghosting the slots with something not needed, to outright disable the slots, so there is no longer the need to check them.

Speed option:
Slow mode is faster than nearly every other autocrafter, I think even AE2/RS. Doing up to 8 crafts per tick is nothing I would consider slow. I propose the something like slow=1 recipe/t, normal = tier recipes/t, fast stays.

**Comment by josephcsible** [comment]
I'm having trouble reproducing this. Can someone who's having the problem upload a saved game that demonstrates the problem, and only uses the mods RFTools and Lag Goggles?

**Comment by josephcsible** [comment]
I just pushed two commits that will improve performance a lot if your crafters aren't all crafting at 100% capacity all the time.

**Comment by PandaBoy444** [comment]
Does it check the recipe every time it crafts? if so, what if it will only check when you code the recipe in? then every tick it will just delete X amount of that and Y amount of this from the internal buffer and produce Z amount of result, it doesn't sound that costly (not that I really know anything, just an idea).

**Comment by desagas** [comment]
Solution:

I was having this problem in the latest version on the latest version of ATM3. I found that crafting Mystical Agriculture essence into blocks immediately, and them crafting upwards is the ideal way to more than half the lag caused by crafting. There are 3 key points for this to work:

1. Use a tier 3 crafter, and insert the farmed inferium essence.
2. Immediately craft the inferium essence into inferium blocks, and then craft up from there in block form only.
3. Have a 3 or 4 slots dedicated and remembered for all levels of the essence, up to agradditions purple, and output the last block externally.

If you remove even one of these requirements, lag ms goes up. Fast vs Slow had no mean ms difference. This was tested on both single and a server, both brand new, and both with the same seed.

My mean time went from 2500ms, to 1080ms, with 64 essence being delivered every 30 ticks, faster than an 11x11 tier 6 farms will output.

**Comment by zauberparacelsus** [comment]
So, is this bug fixed?

**Comment by McJty** [comment]
I still don't see this as a bug. I think however that in a future version I'll remove the 'fast' option (or at least make it configurable so you can disable it). Otherwise the crafters simply do a lot of work that you would have to do using multiple machines otherwise (causing even more lag)
