### ISSUE TITLE
Unable to remove items contained in a Modular Storage Unit with a Storage Scanner (Connected via XNet)

### ISSUE THREAD

**Issue by Routhinator** [McJtyMods/RFTools#1793]
Issue description:

Unable to remove items contained in a Modular Storage Unit with a Storage Scanner. This is brand new behaviour introduced by the latest update. These two units are connected via the XNet RFTools Storage network type.

Steps to reproduce:

Attach XNet connector to a Modular Storage unit and a Storage Scanne and attempt to withdraw items stored in the Storage Unit. In my case I had about 1084 dimensional shards I was trying to withdraw. I got two stacks out and then could not remove anymore. If I reinsert the shards I can take the same ones back out. 

Moving the shards to another storage system like Storage Drawers allows all of them to be withdrawn.

TBF it could also be an XNet issue since it's the connecting mod. But I've verified all the connection settings are proper and they are are same settings on the drawer controller and the MSU.

Versions:

    Minecraft: 1.12.2
    Forge: 2705
    McJtyLib: 3.0.1
    XNet: 1.7.1
    RFTools Control: 1.9.0
    RFTools: 7.53

Possibly incompatible mods and versions:

    SpongeForge: 3169
    FoamFix: 0.9.9.1-Anarchy
    BetterFPS: 1.4.8

Relevant logs, if any:

Nothing I've noted in the logs yet.

**Comment by McJty** [comment]
Can you show a screenshot of the storage scanner gui?

**Comment by Routhinator** [comment]
Sure Thing:

![2018-06-22_06 19 18](https://user-images.githubusercontent.com/727535/41778745-88771470-75e4-11e8-9ce0-6f4250dc216b.png)

**Comment by McJty** [comment]
I would avoid using a drawer controller like that. The drawer controller and the rftools storage combination has been known to cause troubles in the past due to the way the the controller works. It is normally better to link the storage scanners to the individual drawers and not include the controller

**Comment by Routhinator** [comment]
Ok, that's unfortunate but I can work around it. Doesn't explain not being able to pull from the storage units however?

**Comment by McJty** [comment]
Also not if you don't use XNet? Because I see you're still using XNet as range

**Comment by Routhinator** [comment]
I should mention, this setup worked flawlessly until we updated mods. Not sure what triggered this scenario. I'm going to remove the drawer controller and try without XNet again.

**Comment by Routhinator** [comment]
Here we go, XNet is disabled and I've highlight the MSU that I cannot pull from. Even with the direct connection nothing will extract from the second  and third MSUs, the fist and fourth are fine.


![2018-06-22_06 49 19](https://user-images.githubusercontent.com/727535/41780088-9d89c066-75e8-11e8-88ff-07a4871cf8b5.png)
![2018-06-22_06 48 46](https://user-images.githubusercontent.com/727535/41780090-9da60104-75e8-11e8-9349-d1536d5fb108.png)

**Comment by McJty** [comment]
With 'nothing will extract' you mean that you can't pull items out with the gui. right?

**Comment by Routhinator** [comment]
Correct. Inserting works fine. And everything works as expected if I go directly to the unit itself.

**Comment by McJty** [comment]
Very strange... I will try to reproduce this later

**Comment by Routhinator** [comment]
Such a weird issue to troubleshoot. I managed to fix the two completely non-functional MSU's by emptying them, breaking them, changing the storage module, and replacing them. I put the stuff from them in one of the units that worked and now that one seems to be partially acting up. Now it's only specific items from that storage unit that are acting up.  I can extract black concrete, but I cannot extract black concrete powder. :/

**Comment by McJty** [comment]
Oh that's strange. Would be great if you can find a pattern. Also there is no item filter in the modular storage block?

**Comment by Routhinator** [comment]
No filters of any kind.

**Comment by Routhinator** [comment]
Still trying to find a pattern here. I rolled back the recent update we did for your mods and found the issue was unchanged, then updated to the releases from 3 days ago and found it unchanged. 

So far I've found that the following items seem to be consistent in not being able to be pulled from the storage scanner:

- Black Concrete Powder
- Carrots
- Dimensional Shards

**Comment by Routhinator** [comment]
Took this to a local game and boiled the issue down some more. Local game takes out SpongeForge and Permissions plugins from the picture.

Reproduced it easily with 1 Scanner, 3 MSUs with Tier 3 disks and Storage Drawers, with Black Concrete and Black Concrete Powder and Carrots. Was able to put things in through the scanner, but could not take them back out.

**Comment by Routhinator** [comment]
Finally narrowed this down to 6 mod candidates, working through it and should have an update with the culprit soon.

**Comment by Routhinator** [comment]
This problem is somehow caused by Astral Sorcery 1.9.1 on 1.12.2, rolling Astral Sorcery back to 1.8.10 resolves the issue.

These two mods operate in two seemingly very seperate spaces so I'm not sure how this conflict is occurring, but I'm guessing Astral Sorcery is doing something funky.

**Comment by Routhinator** [comment]
Astral Sorcery seems to use some sort of ephemeral network similar to the RFTools scanner.. I wonder if the two are bumping into each other somehow.

**Comment by Doomgull** [comment]
Starlight network has nothing to do with anything except active starlight connections, so no, that is not part of it.

Moving beyond 1.8.10 AS does invoke a new system (amulet) iterating items to get stack sizes during pack load, but I believe that was the only thing changed relating to items outside AS.

**Comment by Doomgull** [comment]
So, some other things learned: vanilla double chest with a single stack of carrots within scanner range causes the same issue, as it reports as 128 carrots vs the 64 it actually is. It's crossing the 127 item threshold. Vanilla cobble stairs, same deal.

**Comment by redaktiv** [comment]
I got the same problem with a storage scanner and a colossal chest. Netherrack, quartz, black quartz are a few of the items I can't pull in the scanners GUI

**Comment by McJty** [comment]
Thanks for all the feedback. I'm not ignoring this. Just collecting information on how to fix this (if it is my side)

**Comment by Woodstove** [comment]
Glad others have experienced this same problem. 

I use a room full of modular storage blocks with a scanner in the center detecting them all. I'm *not* using xnet, everything is at a range of 7 blocks from the scanner. 

I can insert and withdraw items through the scanner, terminal, or tablet but some items stop being removable. This has just started happening since the latest update as far as I can tell. 

The items that stop being removable through the scanner have all been stackable items such as dirt, ingots, logs, redstone (blocks and dust), clay, etc. They are still available to the built-in crafting table but I can't retrieve them into my inventory. If I want to access the items once this happens I have to manually take them from the inventory they're stored in.

I've found that sometimes pulling some out manually and then putting them back in allows the recently replaced ones to be retrieved through the scanner but this is temporary. I'll try to remove the same things later and the same issue will occur.

**Comment by McJty** [comment]
This has me totally baffled... I cannot reproduce this no matter what I do. Is this single player or server btw? Also from what version on did this start fo fail?

**Comment by McJty** [comment]
Ok. a few questions and an experiment.

a) does it fail from the storage tablet and from the scanner directly or only from the tablet?
b) does requesting a single item work in all cases (i.e. shift click)

Also I made a debug version to help diagnose this problem which is available here:

http://jenkins.k-4u.nl/job/RFTools%201.12/lastSuccessfulBuild/artifact/build/libs/rftools-1.12-7.54.jar

It would help a lot if you could try to reproduce this issue with this version. In the log it should show 'REQUEST ATTEMPT' blocks. I'm interested in those. Thanks!

**Comment by redaktiv** [comment]
a) I've only used the storage scanner with a colossal chest.
b) No requesting single item fails too. I tried it with over 200 clay in the colossal chest. Single player world. Both stack and single item failed. A lot of other item worked though. 

I've tried this in both single player (Mech and Magic) and on the Mech and Magic official server.

Version used is 7.54

**Comment by McJty** [comment]
a) I mean do you use the storage scanner directly or through the tablet?

The version I linked is a special debug version. If you can I'm very interested if you can reproduce it with that version and with the debug output

**Comment by Doomgull** [comment]
So...using Astral Sorcery 1.9.2 and your debug version of the 7.54 jar, I cannot get it to reproduce anymore in single player.

Reverting back to AS 1.9.1 returns the issue in the exact same world.

I expect it was a problem relating to the Amulet-Capability being attached to "empty" itemstacks due to a code error that was fixed in AS 1.9.2.

**Comment by McJty** [comment]
Ok, but others had the problem using only rftools I thought. So if they can still reproduce it then I'm still interested in those results

**Comment by Doomgull** [comment]
I believe all the other entries in this thread so far also had astral sorcery involved, because of the pack they were using. I may be mistaken, though.

**Comment by redaktiv** [comment]
Astral Sorcery is in Mech and Magic so I use that. Version 1.9.1
Will update to 1.9.2 solve this issue?

**Comment by Doomgull** [comment]
It did in my tests, but that was only rftools/as, not the mech and magic pack. Would be good to confirm there wasn't another possible interaction at fault, I would imagine.

**Comment by Woodstove** [comment]
I'll first say that the problem occurs using the tablet OR the scanner. Doesn't matter which. 

When I first encountered this problem it was on a multiplayer server running the latest version of the DW20 pack. I just tested it in a brand new DW20 single player world by cheating in 3 modular storage units with tier 3 modules, a storage scanner, a tablet, and a bunch of dirt. 

I tested at both the tablet and the scanner and the results were the same so I'm just going to say scanner from here out.

I dropped all the starter books and random seeds that popped into my inventory into the scanner. Those were easily removed through the scanner. 

I dropped 1 stack of dirt into the scanner and it was easily removed. I added small amounts of dirt in increments and kept testing whether it could be removed. The conclusion is definitely that the problem occurs as soon as the stack reaches 128. At 127 I can remove all the dirt. At 128 and above, I cannot remove any dirt through the scanner.

I also tried splitting the stacks among inventories, thinking that maybe it's just if the dirt in a single inventory >= 128 but, no. Having 64 in one modular storage unit and 64 in another, no dirt is removable through the scanner. Having 64 in one and 63 in another, all dirt can be removed through the scanner normally. 

I haven't had an opportunity to test with your debug version yet but as soon as I get enough pc time, I will.

**Comment by Doomgull** [comment]
@Woodstove can you test with msnually updating AS to 1.9.2?

**Comment by McJty** [comment]
So any news? Is this bug still there? Anyone has been able to test this with my debug version?

**Comment by redaktiv** [comment]
For me the bug is fixed with updating  AS to 1.9.2. I can now completely use this wonderful mod again. And I learned there was an tablet.

**Comment by Routhinator** [comment]
Sorry @McJty I will be testing this tommorow. I have been very busy.

**Comment by Woodstove** [comment]
My apologies as well @McJty , I have been traveling for work and unable to get on Minecraft. Probably going to be another week or two before I can.

**Comment by Routhinator** [comment]
@McJty @Doomgull Confirmed fixed with 1.9.3
